---

- hosts: all
  become: true 
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      state: absent
      autoremove: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: nagios_centos
  become: true 
  roles:
    - name: nagios_centos

- hosts: nagios_ubuntu
  become: true
  roles: 
    - name: nagios_ubuntu
